name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@master
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - run: mkdir out
    - run: mv target/RC24-Bot.jar out/
    - uses: actions/upload-artifact@master
      with:
        name: RC24-Bot
        path: out
